### ISSUE TITLE
Documentation link in nav should respond to version for doc you're currently on

### ISSUE THREAD

**Issue by codyburleson** [CarbonLDP/carbonldp-website#177]
If you are on a page using the alpha version and you click the main Documentation link in the primary navigation, it switches you back to the previous version documentation (i.e. the URL isn't smart, but static to only one version of the documentation, it seems). Ideally all of this is cookie driven or something where once you select a version, all pages show for that version unless and until you change the preferred platform version again.

**Comment by jgf20** [comment]
Yes, the URL is static. The functional design of the documentation links in the navigation menu is that it will always redirect you to the "current version" of the documentation, which refers to the most stable version of the platform. Since there are only two versions, it seems that it redirects you to the previous one, but it is actually redirecting you to the version that has the label:"current" assigned in the website configuration.  Overall, the links are working as expected, in order to fix this issue a redesign of the functionality will have to take place.

**Comment by codyburleson** [comment]
With that explanation, I can see the logic in how it works today. I'm closing the issue and we can open another later if we learn from additional users that it is problematic.
