### ISSUE TITLE
TypeScript error related to type provided for listMembers method in example of "Membership Relation" section

### ISSUE THREAD

**Issue by andynice** [CarbonLDP/carbonldp-website#201]
When using this line of the example
`return project.listMembers<Task>();`

a TypeScript error is displayed:

`TS2558: Expected 0 type arguments, but got 1.`

and from the source code of the PersistedDocument it comes like:
`listMembers(requestOptions: HTTP.Request.Options): Promise<[Class[], HTTP.Response.Class]>;`

**Comment by roddolf** [comment]
The correct code must be:
`return project.listMembers();`

And this is because the this method only retrieves shallow documents (`PersistedDocument.Class`), so it does not accept a generic type.

But there is an error in the parameters of the method; the `requestOptions` must be optional.
I will open an issue in the SDK about this.

**Comment by roddolf** [comment]
See CarbonLDP/carbonldp-js-sdk#209

**Comment by MiguelAraCo** [comment]
Fixed
