### ISSUE TITLE
Improve website loading performance (lazy loading?)

### ISSUE THREAD

**Issue by codyburleson** [CarbonLDP/carbonldp-website#87]
The website takes a long time to load. It seems like it's because it's loading everything all at once. I'm not sure the solution. Do we need to use lazy loading so that we only load modules from certain pages when the users navigate there?

**Comment by MiguelAraCo** [comment]
Making that optimization isn't as easy as it could seem. Lazy loading isn't the problem. Bundling different pieces of the source code is. Now, what's the desired outcome? Right now I'm seeing a load time of 8s when first loading the website and after that 4s by using cache. We should define what's the maximum accepted loading time and work towards that.

The reason I assigned it to me is because the bundle system is somewhat complex and I've wasted enough time working with it to make Jimena or Alvaro waste it again.

**Comment by codyburleson** [comment]
2 seconds is the acceptable standard for static web pages. 4-5 would be an improvement and would do.

**Comment by MiguelAraCo** [comment]
The loading time has been improved to 4~5s. I won't close the issue but I'll lower its priority.

**Comment by MiguelAraCo** [comment]
We'll disable app-dev to lower both the size and the logic needed to bootstrap the website. The progress of this task can be tracked here: #97

**Comment by codyburleson** [comment]
Closing this issue since the website has now been converted to static. Performance issues are no longer a concern.
